[package]
name = "bosn"
version = "0.1.3"
edition = "2024"
rust-version = "1.95"

[lib]
name = "bosn_native"
crate-type = ["cdylib"]

[dependencies]
bosn-service = { path = "../bosn-service" }
bosn-setup = { path = "../bosn-setup" }
kernal-api = { git = "https://github.com/zackees/kernal-api", rev = "fc634e507024d63ccaaf75fa564818b9dcfbff36", version = "=0.1.0", default-features = false, features = ["ipc-async"] }
pyo3 = { version = "=0.29.2", features = ["extension-module"] }
