"""The `bosn-docker` managed Docker/Compose front door."""

from __future__ import annotations

import argparse
import datetime as dt
import subprocess
import sys
import tempfile
from collections.abc import Sequence
from pathlib import Path

from bosn import __version__, daemon, labels
from bosn.compose import ComposeError, content_digest, load_compose
from bosn.registry import Registry


class DockerFrontDoorError(ValueError):
    pass


def compose_to_manifest(source: Path) -> str:
    """Translate the portable image/build subset without silently accepting YAML we ignore.

    Reads through the parsed model rather than indentation regexes. The regexes could not
    see YAML: they resolved no anchors, so a service whose `image` arrived through a `<<:`
    merge looked like it had none, and `profiles:` -- the key the acceptance workload in
    #47 opens with -- was reported as an unsupported key rather than parsed.
    """
    try:
        services = load_compose(source).image_pairs()
    except ComposeError as exc:
        raise DockerFrontDoorError(str(exc)) from exc
    if not services:
        raise DockerFrontDoorError("compose file has no supported service image")
    stacks = []
    for name, image in services:
        default = str(len(stacks) == 0).lower()
        stacks.append(f'[stack.{name}]\nimage = "{image}"\ndefault = {default}\n')
    return "# Generated by bosn-docker init; review before committing.\n\n" + "\n".join(stacks)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="bosn-docker", description=__doc__)
    parser.add_argument("--version", action="version", version=__version__)
    sub = parser.add_subparsers(dest="verb")
    init = sub.add_parser("init", help="generate bosn.toml from compose.yaml")
    init.add_argument("--compose", default="compose.yaml")
    init.add_argument("--output", default="bosn.toml")
    compose = sub.add_parser("compose", help="managed Compose subset: up, down, logs, ps")
    compose.add_argument("command", choices=["up", "down", "logs", "ps"])
    compose.add_argument("args", nargs=argparse.REMAINDER)
    compose.add_argument("-f", "--file", default="compose.yaml")
    return parser


def _yaml_scalar(value: str) -> str:
    """Quote a label value so a YAML parser reads it back byte-for-byte.

    Double quotes were the obvious choice and were wrong on Windows: YAML processes escape
    sequences inside them, so a workspace of `C:\\Users\\me` contains `\\U`, which YAML reads
    as the start of an 8-hex-digit unicode escape and rejects outright. Compose therefore
    could not parse its own generated overlay on the platform bosn is developed on.

    Single-quoted YAML performs no escape processing at all; the only special character is
    the quote itself, escaped by doubling.
    """
    return "'" + value.replace("'", "''") + "'"


def _compose_overlay(registry_id: str | Registry, compose: Path) -> Path:
    """Generate an ephemeral Compose overlay that labels every resource Compose creates.

    Services, top-level volumes, and top-level networks all get a full label
    contract. Compose's implicit `default` network is labeled too, since it is
    created whenever a service doesn't opt out -- even when the file declares no
    `networks:` section at all. Anonymous service-level volumes have no top-level
    key to attach labels to, so they cannot be governed through this overlay; the
    front door refuses to run rather than let them come up unlabeled.
    """
    if isinstance(registry_id, Registry):
        registry_id = registry_id.registry_id
    try:
        parsed = load_compose(compose)
    except ComposeError as exc:
        raise DockerFrontDoorError(str(exc)) from exc
    names = list(parsed.services)
    if not names:
        raise DockerFrontDoorError("compose file has no services")
    volume_names = list(parsed.volumes)
    network_names = list(parsed.networks)
    anonymous = [
        f"{service.name}:{mount}"
        for service in parsed.services.values()
        for mount in service.anonymous_volumes
    ]
    if anonymous:
        raise DockerFrontDoorError(
            "compose file declares anonymous service volumes, which Compose names at "
            "runtime -- there is no stable key an overlay can attach labels to, so they "
            f"would come up ungoverned: {', '.join(anonymous)}; declare them under a "
            "top-level `volumes:` entry using short `name:/path` syntax instead"
        )
    created = dt.datetime.now(dt.UTC).isoformat().replace("+00:00", "Z")
    workspace = str(compose.parent.resolve())
    # Every Compose resource used to carry the constant generation "compose", so every
    # project on the machine shared one generation string and nothing could ever be
    # superseded: editing the compose file rolled nothing, and the old resources stayed
    # current forever. A content digest gives Compose the same identity the manifest path
    # already has -- two invocations are compatible iff their digests are byte-equal.
    generation = content_digest(compose)

    def label_block(resource_names: list[str], kind: str) -> list[str]:
        block: list[str] = []
        for name in resource_names:
            contract = labels.ResourceLabels(
                registry=registry_id,
                kind=kind,
                stack=name,
                generation=generation,
                scope="stack",
                workspace=workspace,
                created=created,
            )
            block += [f"  {name}:", "    labels:"]
            block += [
                f"      {key}: {_yaml_scalar(value)}" for key, value in contract.to_dict().items()
            ]
        return block

    lines = ["services:"]
    lines += label_block(names, "container")
    if volume_names:
        lines.append("volumes:")
        lines += label_block(volume_names, "volume")
    lines.append("networks:")
    governed_networks = network_names if "default" in network_names else [*network_names, "default"]
    lines += label_block(governed_networks, "network")

    handle = tempfile.NamedTemporaryFile(
        mode="w", suffix=".bosn-compose.yaml", delete=False, encoding="utf-8"
    )
    try:
        handle.write("\n".join(lines) + "\n")
        return Path(handle.name)
    finally:
        handle.close()


def _reconcile_after_compose(command: str) -> None:
    """Adopt any labeled-but-unregistered resource left behind by a Compose invocation.

    Runs unconditionally -- on a clean exit, a non-zero exit, and on the way out of a
    KeyboardInterrupt -- because Compose labels (and creates) containers, networks, and
    volumes incrementally as it works through the file. A run that fails partway through
    pulling images, or is killed by Ctrl-C during a foreground `up`, can still leave fully
    labeled resources on the engine that the registry has never heard of: exactly the
    ungoverned accumulation bosn exists to prevent. Gating this on `command == "up" and
    returncode == 0` is precisely how those resources went unregistered.

    Paying for the scan on `down`/`logs`/`ps` too is a non-issue: those commands don't
    label new resources, adoption only registers what is not already known, so the scan
    finds nothing to do and returns immediately.

    A failure here is reported to stderr but never raised. Raising would surface as a
    `DockerFrontDoorError` in `main()`, which maps to exit code 1 regardless of what the
    compose command itself returned -- masking `up`'s real exit status behind a
    bookkeeping error the caller didn't ask about.
    """
    try:
        adopted = daemon.request("compose-adopt")
    except KeyboardInterrupt:
        raise
    except Exception as exc:  # daemon unreachable, IPC failure, etc.
        print(
            f"bosn-docker compose: reconcile after {command} failed: {exc}; "
            "resources created by this run may be unregistered",
            file=sys.stderr,
        )
        return
    if not adopted.get("ok"):
        print(
            f"bosn-docker compose: reconcile after {command} failed: "
            f"{adopted.get('error') or 'compose adoption failed'}; "
            "resources created by this run may be unregistered",
            file=sys.stderr,
        )


def _run_compose(command: str, compose: Path, args: list[str]) -> int:
    if args:
        raise DockerFrontDoorError(f"unsupported compose flag or argument {args[0]!r}")
    reply = daemon.request("status")
    if not reply.get("ok"):
        raise DockerFrontDoorError(str(reply.get("error") or "cannot reach bosn daemon"))
    overlay = _compose_overlay(str(reply["registry_id"]), compose)
    try:
        # The inner try/finally is the load-bearing part: it reconciles whether the
        # subprocess returns normally, raises, or is unwound by a KeyboardInterrupt from
        # Ctrl-C -- the single most likely way a foreground `up` never reaches a clean
        # exit. The outer finally still removes the overlay file in every case.
        try:
            completed = subprocess.run(
                ["docker", "compose", "-f", str(compose), "-f", str(overlay), command], check=False
            )
        finally:
            _reconcile_after_compose(command)
        return completed.returncode
    finally:
        overlay.unlink(missing_ok=True)


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    ns = parser.parse_args(argv if argv is not None else sys.argv[1:])
    if ns.verb is None:
        parser.print_help()
        return 0
    if ns.verb == "init":
        try:
            text = compose_to_manifest(Path(ns.compose))
            output = Path(ns.output)
            if output.exists():
                raise DockerFrontDoorError(f"refusing to overwrite {output}; choose --output")
            output.write_text(text, encoding="utf-8")
        except (OSError, DockerFrontDoorError) as exc:
            print(f"bosn-docker init: {exc}", file=sys.stderr)
            return 1
        print(f"wrote {output}")
        return 0
    if ns.verb == "compose":
        try:
            return _run_compose(ns.command, Path(ns.file), list(ns.args))
        except (OSError, DockerFrontDoorError) as exc:
            print(f"bosn-docker compose: {exc}", file=sys.stderr)
            return 1
    return 2
