"""The `bosn-docker` managed Docker/Compose front door."""

from __future__ import annotations

import argparse
import re
import sys
from collections.abc import Sequence
from pathlib import Path

from bosn import __version__


class DockerFrontDoorError(ValueError):
    pass


def compose_to_manifest(source: Path) -> str:
    """Translate the portable image/build subset without silently accepting YAML we ignore."""
    lines = source.read_text(encoding="utf-8").splitlines()
    services: list[tuple[str, str]] = []
    current: str | None = None
    in_services = False
    for raw in lines:
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        if raw == "services:":
            in_services = True
            continue
        if not in_services:
            continue
        service = re.match(r"^  ([A-Za-z0-9_-]+):\s*$", raw)
        if service:
            current = service.group(1)
            continue
        image = re.match(r"^    image:\s*['\"]?([^'\"\s]+)", raw)
        if image and current:
            services.append((current, image.group(1)))
            continue
        if raw.startswith("    ") and current and not raw.strip().startswith(("image:", "build:")):
            raise DockerFrontDoorError(f"unsupported compose key {raw.strip().split(':', 1)[0]!r}")
    if not services:
        raise DockerFrontDoorError("compose file has no supported service image")
    stacks = []
    for name, image in services:
        default = str(len(stacks) == 0).lower()
        stacks.append(f'[stack.{name}]\nimage = "{image}"\ndefault = {default}\n')
    return "# Generated by bosn-docker init; review before committing.\n\n" + "\n".join(stacks)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="bosn-docker", description=__doc__)
    parser.add_argument("--version", action="version", version=__version__)
    sub = parser.add_subparsers(dest="verb")
    init = sub.add_parser("init", help="generate bosn.toml from compose.yaml")
    init.add_argument("--compose", default="compose.yaml")
    init.add_argument("--output", default="bosn.toml")
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    ns = parser.parse_args(argv if argv is not None else sys.argv[1:])
    if ns.verb is None:
        parser.print_help()
        return 0
    if ns.verb == "init":
        try:
            text = compose_to_manifest(Path(ns.compose))
            output = Path(ns.output)
            if output.exists():
                raise DockerFrontDoorError(f"refusing to overwrite {output}; choose --output")
            output.write_text(text, encoding="utf-8")
        except (OSError, DockerFrontDoorError) as exc:
            print(f"bosn-docker init: {exc}", file=sys.stderr)
            return 1
        print(f"wrote {output}")
        return 0
    return 2
