[package]
name = "bosn-generation"
version = "0.1.0"
edition = "2024"
rust-version = "1.95"

[dependencies]
bosn-core = { path = "../bosn-core" }
kernal-api = { git = "https://github.com/zackees/kernal-api", rev = "fc634e507024d63ccaaf75fa564818b9dcfbff36", version = "=0.1.0", default-features = false, features = ["hash-sha256", "fs"] }
serde_json = "=1.0.149"

[dev-dependencies]
tempfile = "=3.27.0"
